spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password: sa
    generate-unique-name: false
    name: tacocloud
  thymeleaf:
    cache: false
  jpa:
    show-sql: true
    defer-datasource-initialization: true