spring:
  datasource:
    generate-unique-name: false
    name: tacocloud

server:
  port: 8443
  ssl:
    key-store: file:///home/patryk/IdeaProjects/spring-in-action/05-Configuration/src/main/java/tacos/keys/mykeys.jks
    key-store-password: letmein
    key-password: letmein

taco:
  orders:
    pageSize: 10

---
spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password: sa
    generate-unique-name: false
    name: tacocloud
  thymeleaf:
    cache: false
  jpa:
    show-sql: true
    defer-datasource-initialization: true
  config:
    activate:
      on-profile:

logging:
  level:
    tacos: WARN